config/routes.rb
GottaGo::Application.routes.draw do

  get 'splash' => 'home#email_capture'
  post 'reservation' => 'reservation#create'

  resources :cities, only: [:show]

  resources :interests, only: [:show]

  get "comments/:id", to: 'comments#show'
  post "comments" => 'comments#create'

  get "conversations/get-status/:id", to: 'conversations#get_status'
  get "conversations/update-status", to: 'conversations#update_status'
  resources :conversations do
    get :autocomplete_user_name, on: :collection
  end

  get "theme/:id", to: 'theme#show'
  post "theme" => 'theme#create', :as => :create_theme

  get "theme_category", to: 'theme_category#index'

  resources :activity_categories, only: [:index] do
    get "activities/end-time(/:time)", to: 'activities#end_time'
    get "activities/explore", to: 'activities#explore', :as => :activities_explore
  end
  get "activities/explore", to: 'activities#explore', :as => :activities_explore
  get "activities/:user_id/user", to: 'activities#index', :as => :user_activities
  resources :activities, only: [:index, :show, :create]

  get "activity-join/:id", to: 'activity_join#join'
  
  get "curiosities", to: 'curiosity#index', :as => :curiosities
  get "curiosity/:id", to: 'curiosity#curious'

  resources :notifications, only: [:index]

  resources :friends, only: [:index, :show] do
    member do
      get :requests, to: 'friends#requests'
    end
    collection do
      get :explore, to: 'friends#explore'
    end
  end
  resources :friendships, only: [:create, :update, :destroy]

  resources :activity_categories, only: [:index, :show]

  resources :profiles, only: [:show, :index]
  resources :signup_wizard

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'authenticate', to: 'home#index', as: :authenticate
  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks",
    :registrations      => "registrations",
    :sessions           => "sessions",
    :passwords          => "passwords",
    :confirmations      => "confirmations"
  }
  as :user do 
    get "/profile/edit" => "registrations#edit", as: :edit_user_profile
    get "/users"        => "registrations#edit"
  end
  devise_scope :user do #custom devise controller actions
    post :remove_avatar, 
         to: 'registrations#remove_avatar', 
         as: :remove_avatar
  end

  authenticated :user do
    root :to => "cities#show", as: :authenticated_root, defaults: { name: 'Los Angeles, CA, United States' }
  end
  root :to => "cities#show", defaults: { name: 'Los Angeles, CA, United States' }

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_user!
  before_filter :get_friends, only: [:index, :explore]

  def explore
  end

  def index
    @all_friends = @user.get_friends(
      is_limit: false
    ).paginate(
      page: params[:page]
    )
  end

  def show
    @user = User.find params[:id]
    @all_friends = @user.friends.paginate(
      page: params[:page]
    )
  end

  def requests
    self.parse_params
    @suggestions = User
      .search(@suggestion_search_params)
    @suggestions_friends = @suggestions.first(8)
    @search = User
      .filter(current_user)
      .search(params[:search])
    @discovered_friends = @search
      .paginate(:page => params[:page])

    @requested_friends = current_user.get_friend_request
      .paginate(:page => params[:page])

  end

  def parse_params
    @location_contains = ""

    unless params[:search].blank?
      @location_contains = params[:search][:location_contains]
      params[:search][:location_contains] = ""

      @searched_sex = params[:search]['sex_equals']
      if params[:search]['sex_equals'] == 'Both'
        params[:search]['sex_equals'] = ''
      end
      @suggestion_search_params = params[:search].clone;
      @suggestion_search_params['sex_equals'] = ''
    end
  end

  private
    def get_user!
      if params[:id] # if there is no user id in params, show current one
        @user = User.find(params[:id])
      elsif user_signed_in? and params[:search].blank?
        @user = current_user
      elsif user_signed_in? and !params[:search].blank?
        @user = current_user
        @from_search_or_not_authorithed_user = true
      else
        @from_search_or_not_authorithed_user = true
      end
    end

    def get_friends
      self.parse_params

      @search = User
        .filter(current_user)
        .where("users.id != ?", current_user.id)
        .where('users.confirmed_at is NOT NULL OR users.provider is NOT NULL')
        .search(params[:search])

      @suggestions = User
        .filter(current_user)
        .where("users.id != ?", current_user.id)
        .where('users.confirmed_at is NOT NULL OR users.provider is NOT NULL')
        .limit(8)
        .search(@suggestion_search_params)
      @suggestions_friends = @suggestions.all
      
      @discovered_friends = @search
        .paginate(:page => params[:page])
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_explore_friends_nav.html.haml
- if user_signed_in?
  - if @user.id == current_user.id
    %ul.nav.nav-pills.friends-navigation.explore-friends-navigation.decored.btn.btn-grey

      - path = explore_friends_path(id: @user.id, all: 't')
      %li.show-all-friends{ class: request.fullpath == path ? 'active' : ''}
        =link_to "All", path

      - path = explore_friends_path(id: @user.id, search:{ created_at_gt: (Time.now - 7.days) })
      %li.show-new-friends{ class: request.fullpath == path ? 'active' : '' }
        =link_to "Newest", path

      - path = explore_friends_path(:id => @user.id, search: { activity_join_user_id_is_not_null: true, activity_join_created_at_gt: (Time.now - 14.days) })
      %li.show-going-places{ class: request.fullpath == path ? 'active' : '' }
        =link_to "Going Places", path
  - else
    .row.text-center
      %h2.decored All of #{ @user.name}'s Friends
      

app/views/friends/_form.html.haml
= simple_form_for(@friend) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/friends/_friend_item.html.haml
.col-sm-20
  .friend-list-single-item 
    =link_to profile_path(friend) do
      .friend-avatar
        = image_tag friend.avatar_url(:thumb)
        .friend-item-wrap
          .friend-name
            - name = friend.fullname.try(:truncate, 19)
            - age = ''
            - if friend.age.to_s.length == 2
              - age = ", " + friend.age.to_s
            = name + age
          .friend-city
            = friend.location.try(:truncate, 25)
    .interests.col-sm-12
      .row
        - if friend.interests.uniq.size > 0
          - friend.interests.limit(4).uniq.each do |interest|
            .col-sm-6.interest-tag
              %div= interest.name.try(:truncate, 9)
    .action-buttons
      .row
        - if signed_in_and_not_current? friend.id
          - if friends?(friend.id) != true
            =link_to friendships_path(:friend_id => friend.id), :method => :post, title: "Add to friends", class: 'add-to-friend-button col-sm-6' do
              %button.btn.btn-lg.btn-default{:type => "button", :class=>"btn-grey"}
                %span.glyphicon.glyphicon-plus
          - else
            =link_to friendship_path(id: @user.get_friendship(friend_id: friend.id)[0].id, friend_id: friend.id), :method => :delete, title: "Remove from friend", class: 'remove-from-friend-button col-sm-6' do
              %button.btn.btn-lg.btn-default{:type => "button", :class=>"btn-grey"}
                %span.glyphicon.glyphicon-remove
        - if user_signed_in?
          =link_to new_conversation_path(:receiver_id => friend.id), class: 'send-message-button col-sm-6' do
            %button.btn.btn-lg.btn-default{:type => "button", :title => "Send message", :class=>"btn-grey"}
              %span.glyphicon.glyphicon-envelope

app/views/friends/_friends_nav.html.haml
- if user_signed_in?
  - if @user.id == current_user.id
    %ul.nav.nav-pills.friends-navigation.decored.btn.btn-grey
      %li.show-all-friends{ class: request.fullpath == friends_path(:id => @user.id) ? 'active' : ''}
        =link_to "All Friends", friends_path(:id => @user.id)
        %li.show-new-friends{ class: request.fullpath == requests_friend_path(:id => @user.id) ? 'active' : '' }
          =link_to "Friend request", requests_friend_path(:id => @user.id)
  - else
    .row.text-center
      %h2.decored All of #{ @user.name}'s Friends

app/views/friends/_search_friends_form.html.haml
.container
  .row
    .search-form-wrap.col-sm-8.col-sm-offset-2
      = form_for @search, url: friends_path() do |f|
        .row
          .form-group
            .col-sm-4
              = f.text_field :name_or_interests_name_contains, placeholder: "Search by name or interest", class: 'form-control'
            .col-sm-3
              = f.text_field :location_contains, placeholder: "Near?", class: 'form-control', value: @location_contains
              = f.hidden_field :loc_lat_gt, required: false, value: ''
              = f.hidden_field :loc_lng_gt, required: false, value: ''
              = f.hidden_field :loc_lat_lt, required: false, value: ''
              = f.hidden_field :loc_lng_lt, required: false, value: ''
            .col-sm-3
              = f.select :sex_equals , [['Men', 'Male'], ['Women', 'Female'], ['Both', 'Both']], :selected => @searched_sex, class: 'form-control'
            .col-sm-2
              = f.submit "Search", class: 'btn btn-pink', style: 'width: 100%; padding: 6px 0;'



     

app/views/friends/explore.html.haml
%section.photo-explore-friends
  .row
    .col-sm-12
      %img.category-banner{ src: asset_path('discover-friends.jpg') }
  .overlay
    .container
      .row
        .col-sm-12
          %h1 Discover Friends
          -#
            .friend-search
              =render 'search_friends_form'

%section.all-friends
  .container
    -#
      .row
        .col-sm-12.suggestions.text-center
          %h2.decored Our Suggestion
          .suggestions-list.text-center
            - if @suggestions_friends.count > 0
              - @suggestions_friends.uniq.each do |friend|
                =link_to profile_path(friend) do
                  .col-sm-2.user-profile
                    .col-sm-12.user-avatar
                      =link_to profile_path(friend) do
                        = image_tag friend.avatar_url(:thumb), class: ''
                        - unless friend.about.blank?
                          %span.suggestion-tooltip 
                            = friend.about
            - else 
              .row.text-center
                %h2.grey-msg No friends exist

    -#
      .row.text-centered
        =render 'explore_friends_nav'

    .row
      .col-sm-12.friends-list.all
        - if @discovered_friends.uniq.count > 0
          - @discovered_friends.uniq.each do |friend|
            =render 'friend_item', friend: friend
          .col-md-12.text-center
            =will_paginate @discovered_friends
        - else
          .row.text-center
            %h2.grey-msg No friends

    %p.back-top
      %a{:href => ".top"}
        %span>
        Back to Top

app/views/friends/index.html.haml
%section
  .col-md-12.photo-body.discover-friends
    .col-md-12.discover-title Discover... New Friends
    .friend-search
      =render 'search_friends_form'

%section.all-friends
  .container
    .row
      .col-md-12.suggestions.text-center
        %h2.decored Our Suggestion
        .suggestions-list.text-center
          - if @suggestions_friends.count > 0
            - @suggestions_friends.uniq.each do |friend|
              =link_to profile_path(friend) do
                .col-md-2.user-profile
                  .col-md-12.user-avatar
                    =link_to profile_path(friend) do
                      = image_tag friend.avatar_url(:thumb), class: ''
                      - unless friend.about.blank?
                        %span.suggestion-tooltip 
                          = friend.about
          - else 
            .row.text-center
              %h2.grey-msg No friends exist
    .row.text-centered
      =render 'friends_nav'
    .row
      .col-md-12.friends-list.all
        .col-md-12
          - if @all_friends.uniq.count > 0
            - @all_friends.uniq.each do |friend|
              =render 'friend_item', :friend=>friend
            .col-md-12.text-center
              =will_paginate @all_friends
          - else
            .row.text-center
              - if @user.id == current_user.id
                %h2.grey-msg You have no friends
              - else
                %h2.grey-msg #{ @user.name} have no friends
                

app/views/friends/requests.html.haml
%section
  .col-md-12.photo-body.discover-friends
    .col-md-12.discover-title Discover... New Friends
    .friend-search
      =render 'search_friends_form'

%section.all-friends
  .container
    =render 'friends_nav'
    .col-md-12.friends-list.new
      - if @user.inverse_friendships.any?
        - if @requested_friends.size > 0
          - @requested_friends.each do |friend|
            .clearfix.friend-list-single-item
              .col-md-12.friend-avatar
                = image_tag friend.avatar_url(:thumb), class: ''
              .friend-item-wrap
                .friend-name
                  = friend.fullname.try(:truncate, 19)
                .friend-city
                  = friend.location.try(:truncate, 25)
              .col-md-12.action-buttons
                - if signed_in_and_not_current? friend.id
                  =link_to friendship_path(id: @user.get_friendship(friend_id: friend.id)[0].id, friend_id: friend.id), :method => :put, title: "Confirm request", class: 'add-to-friend-button' do
                    %button.btn.btn-lg.btn-grey.btn-default{:type => "button"}
                      %span.glyphicon.glyphicon-plus
                =link_to new_conversation_path(:receiver_id => friend.id), class: 'send-message-button' do
                  %button.btn.btn-lg.btn-grey.btn-default{:type => "button", :title => "Send message"}
                    %span.glyphicon.glyphicon-envelope
          .col-md-12.text-center
            =will_paginate @requested_friends
        - else
          .row.text-center
            %h2.grey-msg You have no friends request
      - else
        .row.text-center
          %h2.grey-msg You have no friends request
          

app/views/friends/show.html.haml
.user-info-section.profile-friends
  = render 'profiles/header', user: @user
  = render 'profiles/header_bottom_nav', user: @user, scroll_interests: true
  %section.all-activities
    .container
      .row.text-center
        %h3.decored All Friends
      .row
        .col-md-12
          .row.friends-list.all
            - if @all_friends.size > 0
              .col-md-10.col-md-offset-1.borderize.whitebg.roundize
                - @all_friends.each do |friend|
                  =link_to profile_path(friend) do
                    .col-md-4.friend-list-item
                      .row
                        .col-md-6.friend-avatar
                          = image_tag friend.avatar_url(:thumb), class: ''
                        .col-md-6
                          .friend-name
                            = friend.name
                          .friend-city
                            = friend.location.try(:truncate, 25)
              .col-md-12.text-center
                =will_paginate @all_friends
            - else 
              - if @user.id == current_user.id
                .row.text-center
                  %h2.grey-msg You have no friends
              - else
                .row.text-center
                  %h2.grey-msg #{ @user.name} have no friends
              %p.back-top
                %a{:href => ".top"}
                  %span>
                  Back to Top
            