config/routes.rb
GottaGo::Application.routes.draw do

  get 'splash' => 'home#email_capture'
  post 'reservation' => 'reservation#create'

  resources :cities, only: [:show]

  resources :interests, only: [:show]

  get "comments/:id", to: 'comments#show'
  post "comments" => 'comments#create'

  get "conversations/get-status/:id", to: 'conversations#get_status'
  get "conversations/update-status", to: 'conversations#update_status'
  resources :conversations do
    get :autocomplete_user_name, on: :collection
  end

  get "theme/:id", to: 'theme#show'
  post "theme" => 'theme#create', :as => :create_theme

  get "theme_category", to: 'theme_category#index'

  resources :activity_categories, only: [:index] do
    get "activities/end-time(/:time)", to: 'activities#end_time'
    get "activities/explore", to: 'activities#explore', :as => :activities_explore
  end
  get "activities/explore", to: 'activities#explore', :as => :activities_explore
  get "activities/:user_id/user", to: 'activities#index', :as => :user_activities
  resources :activities, only: [:index, :show, :create]

  get "activity-join/:id", to: 'activity_join#join'
  
  get "curiosities", to: 'curiosity#index', :as => :curiosities
  get "curiosity/:id", to: 'curiosity#curious'

  resources :notifications, only: [:index]

  resources :friends, only: [:index, :show] do
    member do
      get :requests, to: 'friends#requests'
    end
    collection do
      get :explore, to: 'friends#explore'
    end
  end
  resources :friendships, only: [:create, :update, :destroy]

  resources :activity_categories, only: [:index, :show]

  resources :profiles, only: [:show, :index]
  resources :signup_wizard

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'authenticate', to: 'home#index', as: :authenticate
  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks",
    :registrations      => "registrations",
    :sessions           => "sessions",
    :passwords          => "passwords",
    :confirmations      => "confirmations"
  }
  as :user do 
    get "/profile/edit" => "registrations#edit", as: :edit_user_profile
    get "/users"        => "registrations#edit"
  end
  devise_scope :user do #custom devise controller actions
    post :remove_avatar, 
         to: 'registrations#remove_avatar', 
         as: :remove_avatar
  end

  authenticated :user do
    root :to => "cities#show", as: :authenticated_root, defaults: { name: 'Los Angeles, CA, United States' }
  end
  root :to => "cities#show", defaults: { name: 'Los Angeles, CA, United States' }

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    conditions = {recipient_id: current_user.id, recipient_type: "User"}
    PublicActivity::Activity.update_all({is_read: true}, conditions)
    get_unread_messages_and_notification
    @notifications = PublicActivity::Activity.where(conditions).order('created_at DESC')
      .paginate(:page => params[:page], :per_page => 10)
  end
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_minimized_not.html.haml
.col-md-12.margin-top5
  %div{ class: "#{ last ? '' : 'border-bottom'}"}
    .col-md-2.paddingles.borderize.roundize3
      = link_to profile_path(notification.owner) do
        = image_tag notification.owner.avatar.url(:thumb)
    .col-md-10
      %p
        = notification.key
        - if notification.trackable_type == 'User'
          = link_to "View #{notification.owner.accost} profile", profile_path(notification.owner), class:"view-back"
        - if notification.trackable_type == 'Activity'
          = link_to notification.trackable.title, activity_path(notification.trackable)
    %div{style: 'clear: both'}

app/views/notifications/_notification.html.haml
.col-md-12.border-bottom.index-message
  .row.no-margin-top
    .col-md-5
      .row.notifications
        .col-md-3
          = link_to profile_path(notification.owner) do
            = image_tag notification.owner.avatar.url(:thumb)
        .col-md-9
          %p.sender= notification.owner.fullname_initials
          %p.sender-location= notification.owner.location_short
    .col-md-4.extra-padding
      %p
        = notification.key
        - if notification.trackable_type == 'User'
          = link_to "View #{notification.owner.accost} profile", profile_path(notification.owner), class:"view-back"
        - if notification.trackable_type == 'Activity'
          = link_to notification.trackable.title, activity_path(notification.trackable)
    .col-md-3
      .row.text-right
        .col-md-12
          .created_at
            %p= l notification.created_at, format: :message
            %p= l notification.created_at, format: :time

app/views/notifications/index.html.haml
= render 'profiles/header', user: current_user, bottom_nav: false
%section.no-margin-top
  .col-md-12.whitebg.fix.border-bottom
    .container
      = render 'conversations/messages_head'
%section
  - if !@notifications.blank?
    .container.borderize.roundize.white
      .row.margin-bottom
        - @notifications.each do |notification|
          - if notification.owner
            = render 'notification', notification: notification
        .col-md-12.text-center
          =will_paginate @discovered_friends
  - else
    .container
      .row.margin-bottom
        %h2.col-md-12.text-center.grey-msg You have no notifications