config/routes.rb
GottaGo::Application.routes.draw do

  get 'splash' => 'home#email_capture'
  post 'reservation' => 'reservation#create'

  resources :cities, only: [:show]

  resources :interests, only: [:show]

  get "comments/:id", to: 'comments#show'
  post "comments" => 'comments#create'

  get "conversations/get-status/:id", to: 'conversations#get_status'
  get "conversations/update-status", to: 'conversations#update_status'
  resources :conversations do
    get :autocomplete_user_name, on: :collection
  end

  get "theme/:id", to: 'theme#show'
  post "theme" => 'theme#create', :as => :create_theme

  get "theme_category", to: 'theme_category#index'

  resources :activity_categories, only: [:index] do
    get "activities/end-time(/:time)", to: 'activities#end_time'
    get "activities/explore", to: 'activities#explore', :as => :activities_explore
  end
  get "activities/explore", to: 'activities#explore', :as => :activities_explore
  get "activities/:user_id/user", to: 'activities#index', :as => :user_activities
  resources :activities, only: [:index, :show, :create]

  get "activity-join/:id", to: 'activity_join#join'
  
  get "curiosities", to: 'curiosity#index', :as => :curiosities
  get "curiosity/:id", to: 'curiosity#curious'

  resources :notifications, only: [:index]

  resources :friends, only: [:index, :show] do
    member do
      get :requests, to: 'friends#requests'
    end
    collection do
      get :explore, to: 'friends#explore'
    end
  end
  resources :friendships, only: [:create, :update, :destroy]

  resources :activity_categories, only: [:index, :show]

  resources :profiles, only: [:show, :index]
  resources :signup_wizard

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'authenticate', to: 'home#index', as: :authenticate
  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks",
    :registrations      => "registrations",
    :sessions           => "sessions",
    :passwords          => "passwords",
    :confirmations      => "confirmations"
  }
  as :user do 
    get "/profile/edit" => "registrations#edit", as: :edit_user_profile
    get "/users"        => "registrations#edit"
  end
  devise_scope :user do #custom devise controller actions
    post :remove_avatar, 
         to: 'registrations#remove_avatar', 
         as: :remove_avatar
  end

  authenticated :user do
    root :to => "cities#show", as: :authenticated_root, defaults: { name: 'Los Angeles, CA, United States' }
  end
  root :to => "cities#show", defaults: { name: 'Los Angeles, CA, United States' }

end

app/helpers/navigation_helper.rb
module NavigationHelper

  def internal_page? (url)
    url = url.sub /\?.*/, ''
    external = [
      '/users/sign_in',
      '/users/sign_up',
      '/signup_wizard/user_info',
      '/signup_wizard/photo',
      '/signup_wizard/choose_interests',
      '/signup_wizard/confirm_profile'
    ]
    if !current_user
      external.push '', '/'
    end
    !external.include? url
  end

end

app/views/layouts/navigation/_authenticated_external.html.haml
.nav-holder.authenticated.external
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-wide
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to image_tag("/assets/logo.png", :style => "height: 30px;"), root_path, class: 'navbar-brand' 
      .collapse.navbar-collapse
        -#
          %ul.nav.navbar-nav.nav-drop
            %li.dropdown
              %a.city-ul{"data-toggle" => "dropdown", href: "#"}
                - if defined?(@city)
                  = @city.get_city_name
                - else
                  Los Angeles
                ▼
              %ul.dropdown-menu.in-nav{"aria-labelledby" => "dLabel", role: "menu"}
                - City.all.each do |city|
                  %li
                    = link_to city.get_city_name, city
        %ul.nav.navbar-nav.pull-right
          = render 'layouts/navigation/links'
    = render 'layouts/navigation/subnav'

app/views/layouts/navigation/_authenticated_internal.html.haml
.nav-holder.authenticated.internal
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-wide
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to image_tag("/assets/logo.png", :style => "height: 30px;"), root_path, class: 'navbar-brand' 
      .collapse.navbar-collapse
        -#
          %ul.nav.navbar-nav.nav-drop
            %li.dropdown
              %a.city-ul{"data-toggle" => "dropdown", href: "#"}
                - if defined?(@city)
                  = @city.get_city_name
                - else
                  Los Angeles
                ▼
              %ul.dropdown-menu.in-nav{"aria-labelledby" => "dLabel", role: "menu"}
                - City.all.each do |city|
                  %li
                    = link_to city.get_city_name, city
        %ul.nav.navbar-nav.pull-right
          = render 'layouts/navigation/links'
    = render 'layouts/navigation/subnav'

app/views/layouts/navigation/_links.html.haml
- if user_signed_in?

- else
  .nav.navbar-nav.sign-in-nav
    %li= link_to 'Sign Up', new_user_registration_path, class: 'green-link'
    %li= link_to 'Login', new_user_session_path
    %li= link_to 'Post Activity', new_user_session_path, class: 'btn btn-pink navbar-btn'
- if user_signed_in?
  %li
    / =link_to requests_friend_path(:id => current_user.id) do
    /   = image_tag '/assets/Friend_requests.png', class: 'new_friends'
    /   %sup.count-of-reguest
    /     - if current_user.get_friend_request.size > 0
    /       =current_user.get_friend_request.size

  %li.dropdown
    %a{"data-toggle" => "dropdown", href: "#"}
      %span
        %img{:src => "/assets/addfriends.png"}
      - if current_user.pending_friend_requests.size > 0
        %sup.count-of-reguest
          = current_user.pending_friend_requests.size

    %ul.dropdown-menu.custom{"aria-labelledby" => "dLabel", role: "menu"}
      - unless current_user.pending_friend_requests.size > 0
        .col-md-12.extra-margin-top
          %li You have no friend requests.
      - else
        .col-md-12
          - current_user.pending_friend_requests.each do |pending_friend_request|
            - pending_friend = current_user.pending_friend(pending_friend_request)
            %li
              %a{:href => profile_path(pending_friend)}
                %span.left_block
                  %img{:src => "http://lorempixel.com/48/48"}/
                %span.right_block
                  %span.name
                    = pending_friend.name
                  / %span.time 4 days ago
              .divider


          %li.dropdown-footer.last-child
            = link_to 'View All', requests_friend_path(:id => current_user.id)

  %li.dropdown
    %a{"data-toggle" => "dropdown", href: "#"}
      %span.glyphicon.glyphicon-globe
      - if @unread_notifications_count.present?
        %sup.count-of-reguest
          = @unread_notifications_count
    %ul.dropdown-menu.custom{"aria-labelledby" => "dLabel", role: "menu"}
      - if @last_notifications.blank?
        .col-md-12.extra-margin-top
          %li You have no notifications
      - else
        - @last_notifications.each do |n|
          - t = (@last_notifications.last == n)
          %li= render 'notifications/minimized_not', notification: n, last: t
          - if t
            .col-md-12
              %li= link_to 'View all', notifications_path, class: 'pull-right'

  %li.dropdown
    %a{"data-toggle" => "dropdown", href: "#"}
      %span.glyphicon.glyphicon-envelope
      - if @unread_messages_count.present?
        %sup.count-of-reguest
          = @unread_messages_count
    %ul.dropdown-menu.custom{"aria-labelledby" => "dLabel", role: "menu"}
      - if @last_messages.blank?
        .col-md-12.extra-margin-top
          %li You have no messages
      - else
        - @last_messages.each do |m|
          - t = (@last_messages.last == m)
          %li= render 'conversations/minimized_mes', receipt: m, last: t
          - if t
            .col-md-12
              %li= link_to 'View all', conversations_path, class: 'pull-right'

  %li.dropdown
    %a.avatar{"data-toggle" => "dropdown", href: "#"}
      %span.glyphicon
      = image_tag current_user.avatar_url(:thumb), class: 'img-circle glyphiuser'
    %ul.dropdown-menu.custom-navs{"aria-labelledby" => "dLabel", role: "menu"}
      .col-md-12.border-bottom
        %li= link_to 'My Profile', [profiles_path, current_user.id].join('/')
      .col-md-12.border-bottom
        %li= link_to 'Post an Activity', '#', data: { target: '#PostActivity', toggle: 'modal' }
      .col-md-12.border-bottom
        %li= link_to 'My Activities', activities_path
      .col-md-12.border-bottom
        %li= link_to 'My Friends', friend_path(current_user)
      .col-md-12.border-bottom
        %li= link_to 'My Curiosities', curiosities_path
      .col-md-12.border-bottom
        %li= link_to 'Edit Profile', edit_user_profile_path(tab: "about")
      .col-md-12.border-bottom
        %li= link_to 'Settings', edit_user_profile_path(tab: "my-account")
      .col-md-12
        %li= link_to 'Logout', destroy_user_session_path, :method=>'delete'

    = render "activities/modal"

  -#
    %li
      .button.btn.btn-pink.marginButton{"data-target" => "#PostActivity", "data-toggle" => "modal"} Post Activity

app/views/layouts/navigation/_subnav.html.haml
.col-md-12.top-nav-header
  %div.text-center
    = link_to 'Explore Activities ▼', activity_categories_path
    - if user_signed_in?
      = link_to 'Discover Friends', explore_friends_path(:id => current_user.id)
    - else
      = link_to 'Sign In', new_user_session_path
      %h2 Test Display

app/views/layouts/navigation/_unauthenticated_external.html.haml
.nav-holder.unauthenticated.external
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-wide
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to image_tag("/assets/logo.png", :style => "height: 30px;"), root_path, class: 'navbar-brand' 
      .collapse.navbar-collapse
        -#
          %ul.nav.navbar-nav.nav-drop
            %li.dropdown
              %a.city-ul{"data-toggle" => "dropdown", href: "#"}
                - if defined?(@city)
                  = @city.get_city_name
                - else
                  Los Angeles
                ▼
              %ul.dropdown-menu.in-nav{"aria-labelledby" => "dLabel", role: "menu"}
                - City.all.each do |city|
                  %li
                    = link_to city.get_city_name, city
        %ul.nav.navbar-nav.pull-right
          = render 'layouts/navigation/links'

app/views/layouts/navigation/_unauthenticated_internal.html.haml
.nav-holder.unauthenticated.internal
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-wide
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to image_tag("/assets/logo.png", :style => "height: 30px;"), root_path, class: 'navbar-brand' 
      .collapse.navbar-collapse
        -#
          %ul.nav.navbar-nav.nav-drop
            %li.dropdown
              %a.city-ul{"data-toggle" => "dropdown", href: "#"}
                - if defined?(@city)
                  = @city.get_city_name
                - else
                  Los Angeles
                ▼
              %ul.dropdown-menu.in-nav{"aria-labelledby" => "dLabel", role: "menu"}
                - City.all.each do |city|
                  %li
                    = link_to city.get_city_name, city
        %ul.nav.navbar-nav.pull-right
          = render 'layouts/navigation/links'